# See https://golangci-lint.run/usage/linters/

linters:
  enable-all: true
  disable:
    # Note: deprecated linters
    - gomnd
    - execinquery
    - exportloopref
    - forbidigo
    # gosimple

linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - "!**/*_a _file.go"
        allow:
          - $gostd
          - github.com/OpenPeeDeeP
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package

  lll:
    line-length: 140
    tab-width: 1

  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - errors.Join(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
    ignoreSigRegexps:
      - \.New.*Error\(
    ignorePackageGlobs:
      - encoding/*
      - github.com/pkg/*
    ignoreInterfaceRegexps:
      - ^(?i)c(?-i)ach(ing|e)