# See https://golangci-lint.run/usage/linters/

linters:
  enable-all: true
  disable:
    # Note: deprecated linters
    - gomnd
    - execinquery
    - exportloopref

linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - "!**/*_a _file.go"
        allow:
          - $gostd
          - github.com/OpenPeeDeeP
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package