services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "collmetr"
      POSTGRES_DB: "collmetricdb"
    ports:
      - "5432:5432"
    volumes:
      - data_sql:/var/lib/postgresql/data   # Persistent data storage

volumes:
  data_sql: