name: test-and-coverage

on: 
  push:
    branches:
      - iter1
      - iter2
      - iter3
      - iter4
      - iter5
      - iter6
      - iter7
      - iter8
      - iter9
      - iter10
      - iter11
      - iter12
      - iter13
      - iter14
      - iter15
      - iter18
  pull_request:
    branches:
      - iter1
      - iter2
      - iter3
      - iter4
      - iter5
      - iter6
      - iter7
      - iter8
      - iter9
      - iter10
      - iter11
      - iter12
      - iter13
      - iter14
      - iter15
      - iter18

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:20-bookworm-slim

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Gather dependencies
        run: go mod download
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}