name: test-and-coverage

on: 
  push:
    branches:
      - main
      - iter1
      - iter2
      - iter3
      - iter4
      - iter5
      - iter6
      - iter7
      - iter8
      - iter9
      - iter10
      - iter11
      - iter12
      - iter13
      - iter14
  pull_request:
    branches:
      - main
      - iter1
      - iter2
      - iter3
      - iter4
      - iter5
      - iter6
      - iter7
      - iter8
      - iter9
      - iter10
      - iter11
      - iter12
      - iter13
      - iter14

jobs:
  build:
     runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v4
    #   - uses: actions/setup-go@v5
    #     with:
    #       go-version: 'stable'
    #   - name: Gather dependencies
    #     run: go mod download
    #   - name: Run coverage
    #     run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
    #   - name: Upload coverage to Codecov
    #     uses: codecov/codecov-action@v5
    #     with:
    #       token: ${{ secrets.CODECOV_TOKEN }}